# Generated by Django 3.2.9 on 2022-01-16 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='content',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='category',
            name='metatitle',
        ),
    ]
