# Generated by Django 3.2.9 on 2022-01-15 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20220115_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='summary_en',
            field=models.TextField(blank=True, null=True),
        ),
    ]
