# Generated by Django 3.2.9 on 2022-03-02 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_article_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='images',
        ),
    ]
