# Generated by Django 3.2.9 on 2022-01-16 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_article_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='language',
            field=models.CharField(choices=[('ar', 'ar'), ('en', 'ar')], default='ar', max_length=7),
        ),
    ]
