# Generated by Django 3.2.9 on 2022-03-02 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_article_images'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('-published_at',), 'permissions': (('change_status', 'Can view article'),), 'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
    ]
