# Generated by Django 3.2.9 on 2022-03-02 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_alter_article_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('-published_at',), 'permissions': (('change_status', 'Can change the status of the article'),), 'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
    ]
