# Generated by Django 3.2.9 on 2022-01-18 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_auto_20220118_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleimage',
            name='article_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='news.article'),
        ),
        migrations.AlterField(
            model_name='articleimage',
            name='image_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='news.image'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_url',
            field=models.ImageField(blank=True, upload_to='articles_images/', verbose_name='image'),
        ),
    ]
