# Generated by Django 3.2.9 on 2022-03-03 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_auto_20220303_2141'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ObjectPermission',
        ),
    ]
