# Generated by Django 3.2.9 on 2022-01-19 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_alter_image_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleimage',
            name='article_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.article'),
        ),
        migrations.AlterField(
            model_name='articleimage',
            name='image_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.image'),
        ),
    ]
