# Generated by Django 3.2.9 on 2022-01-27 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_auto_20220119_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_url',
            field=models.ImageField(upload_to='news/static/news/', verbose_name='image'),
        ),
    ]
