# Generated by Django 3.2.9 on 2022-03-03 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_usercategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercategory',
            name='is_active',
        ),
    ]
