# Generated by Django 3.2.9 on 2022-01-27 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_alter_image_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_url',
            field=models.ImageField(upload_to='news/static/news/articles_images/', verbose_name='image'),
        ),
    ]
